# Branch Protection Configuration
# Copyright: YC-2025Copyright
# Description: Automated branch protection rules

rules:
  # Main branch protection
  main:
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Quality Gate"
          - "Test Suite (16)"
          - "Test Suite (18)" 
          - "Test Suite (20)"
          - "Security Scan"
          - "Build Matrix (ubuntu-latest)"
          - "Build Matrix (windows-latest)"
          - "Build Matrix (macos-latest)"
      enforce_admins: true
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 2
        require_review_from_codeowners: true
      restrictions:
        users: []
        teams: ["core-maintainers"]
        apps: ["dependabot"]
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false

  # Develop branch protection  
  develop:
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Quality Gate"
          - "Test Suite (18)"
          - "Security Scan"
      enforce_admins: false
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        required_approving_review_count: 1
      allow_force_pushes: false
      allow_deletions: false

  # Release branch protection
  "release/*":
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Quality Gate"
          - "Test Suite (18)"
          - "Security Scan"
          - "Performance Benchmark"
      enforce_admins: true
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 2
      restrictions:
        users: []
        teams: ["release-managers"]
      allow_force_pushes: false
      allow_deletions: false